error: Record `transaction.name` when available
Adds a new `transaction.name` field which is recorded when a transaction
is set for the error.

Signed-off-by: Marc Lopez Rubio <marc5.12@outlook.com>